### ISSUE TITLE
parseStyleSheet error

### ISSUE THREAD

**Issue by oswetto** [HtmlUnit/htmlunit-cssparser#10]
Hi @rbri 
This code not work, erorr invalid token "100vh" 

```
String cssText = ".section-actions-hero{height:calc(100vh - 72px)}";
CSSOMParser parser =  new CSSOMParser(new CSS3Parser());
final Reader reader = new StringReader(cssText);
final InputSource is = new InputSource(reader);
parser.parseStyleSheet(is, null);
```
This code work
```
String cssText = ".section-actions-hero{height:calc(100vh - 72px)}";
CSSOMParser parser =  new CSSOMParser(new CSS3Parser());
parser.parseStyleDeclaration(cssText);
```

**Comment by rbri** [comment]
Have you used the latest code / the version i released yesterday?

**Comment by oswetto** [comment]
@rbri yes, 1.7.0 version, last commit 07/11/20 15:31

**Comment by rbri** [comment]
Strange I can't reproduce. Can you please create a pull request with an test case.

Am 8. November 2020 18:08:11 MEZ schrieb Ivan Di Francesco <notifications@github.com>:
>@rbri yes, 1.7.0 version, last commit 07/11/20 15:31
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/HtmlUnit/htmlunit-cssparser/issues/10#issuecomment-723638109

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by oswetto** [comment]
Hi @rbri test case committed in pull request #3

**Comment by oswetto** [comment]
Sorry @rbri i've fixed my problem, i've delete my local repo and download the code. Now work!
