### ISSUE TITLE
Question: LexicalUnitType.SUB_EXPRESSION

### ISSUE THREAD

**Issue by paulushub** [HtmlUnit/htmlunit-cssparser#14]
This type `LexicalUnitType.SUB_EXPRESSION` is never created by the parser. 
It is type about IE's expression() function (example: `top:expression(body.scrollTop + 50 + "px")`)?

**Comment by rbri** [comment]
this was a leftover from SAC seems to be unused since ages, Thanks for noting that.

BTW 
> I did further simplifications by turning CSSValueImpl.java into an abstract class without the value object and making RectImpl.java, RGBColorImpl.java, CounterImpl.java, LexicalUnitImpl.java, etc super class of CSSValueImpl.java.

i'm interested in your changes here, can you highligh this a bit more - or make a pr for this?

**Comment by paulushub** [comment]
> i'm interested in your changes here, can you highligh this a bit more - or make a pr for this?

It is a work in progress in C# (changing the sources and the tests in steps), and trying to remodel the DOM. 
It is currently not on Github, if you wish to see it I could post it here or send it to you by email. Attached is the current state of the model, showing only the current **CSS Values**. Others like Gradients and Transforms are still being defined. I found your codes, when I started looking for ways to fix the color slash-separator, which you have generously fixed recently.

I am planning for a Java version, and was hoping to post it and invite you for a review. PR will results in many breaking changes. But I need the C# version to complete a new work I stated for SVG rendering.

**NOTE:** 
* The **CssUnparsed** class is equivalent to the **LexicalUnitImpl** in the Java code. 
That naming is based on [MDN: CSSUnparsedValue](https://developer.mozilla.org/en-US/docs/Web/API/CSSUnparsedValue), not exactly the same but the idea is similar - custom parser value in this case.
* The inner and private **EmptyValue (extends CssValue)** class, is equivalent to `new CSSValueImpl()` in Java, but read-only.
* Not shown, but there is **CssValueFactory** for creating the values, an extension of what used to be `CSSValueImpl` constructor. 
* There is no `CSSValueImpl.SetCssText`, replaced with `CssValueFactory.Create(string cssText)`. 
* The **CssColorNamed** is used for properties like `background-color: red`, which is parsed to STRING value. The `CssValueFactory` method for creating `CssString` checks for predefined colors; if found `CssColorNamed` value is created instead.
* etc

![ClassDiagram](https://user-images.githubusercontent.com/809351/144717671-f3fd2305-4ad8-4557-b873-71ba78f448af.png)


Currently, trying to improve and update the Java sources so that I do not have to port the generated JavaCC sources anytime soon. By learning from your changes and updates to JavaCC file, I have made some updates too; supporting incoming colors models HWB, LAB/OKLAB, LCH/OKLCH, and Color Space (color-function).

**Comment by paulushub** [comment]
You may not like those color class naming: `CssColorRgb`, `CssColorHsl`, `CssColorNamed` (might prefer `CssRgbColor`, `CssHslColor` etc). But there will be more color classes for HWB, LAB, LCH etc so I want to keep them together in the project navigation panes!
