### ISSUE TITLE
Parse selectors error

### ISSUE THREAD

**Issue by oswetto** [HtmlUnit/htmlunit-cssparser#17]
Hi @rbri, Happy New Year :-)

I've error when parse selectors "div:not(div:nth-last-of-type(1))" or "p a:not(a:first-of-type)"

My Code
```
final CSSOMParser parser = new CSSOMParser(new CSS3Parser());
parser.setErrorHandler(ThrowCssExceptionErrorHandler.INSTANCE);
parser.parseSelectors(selectors);
```

Exception
"Error in pseudo class or element. (Invalid token ":". Was expecting one of: <S>, ")".)"

**Comment by rbri** [comment]
Hi @oswetto , same to you.

Will have a look....

**Comment by rbri** [comment]
had a first look, and from the parser it looks simple to fix. But i have to introduce a real model object for the not pseudo condition. This will require some thinking....

**Comment by rbri** [comment]
Hi @oswetto,

Just made a new snapshot build 1.14.0-SNAPSHOT available.
This one has a dedicated model class for not conditions - NotPseudoClassCondition!

With this the not parsing is much, much improved, we can now have all the complicated selectors inside not. And the Selectivity calculation for not() is also fixed.

Hope that helps - at least for HtmlUnit i have now more tests passing :-)

Please try and give me some hint about your findings....

**Comment by oswetto** [comment]
Thanks @rbri,
works very well
