### ISSUE TITLE
Lookahead(2) causes really poor parser performance

### ISSUE THREAD

**Issue by svschouw-bb** [HtmlUnit/htmlunit-cssparser#19]
Even with the recently improved `:not` handling the performance of the CSS parser is still really poor. Over 50% of the CPU of our HtmlUnit tests is spent parsing CSS, and if I interpret the profiler data correctly the cause is the `LOOKAHEAD(2)` in [CSS3Parser.jj:1111](https://github.com/HtmlUnit/htmlunit-cssparser/blob/master/src/main/javacc/CSS3Parser.jj#L1111)

JavaCC seems to implement `LOOKAHEAD(2)` by just running a side-effect free version of the parser, and as soon as 2 tokens have been correctly parsed, it throws a pre-constructed `LookaheadSuccess` throwable, restores the parser state and starts parsing for real. Throwing exceptions is expensive and the method that throws this exception is really high in the "self-time" of the profiler (actually the method itself is nowhere to be found, but various other methods that call this method are; I presume the compiler inlines the `jj_scan_token(int)` method that does it).

My guess is that the `LOOKAHEAD(2)` is there to differentiate between `div span` (descendant selector) and `div {`. Since the presence of whitespace after the selector (`div`) does not tell you whether you are done parsing selectors yet. My experience with parsers is that in general you want to skip all whitespace from the token stream. This way instead of having to differentiate between `<IDENT> <S> <IDENT>` vs `<IDENT> <S> <LBRACE>` you differentiate between `<IDENT> <IDENT>` vs `<IDENT> <LBRACE>`, making the parser LL(1), which should improve the performance a lot.

Is there any reason to keep the whitespace in the token stream? Is there an annoying CSS feature that requires this?

If I have time I might look into creating a pull request, but my experience with JavaCC is mostly theoretical.

**Comment by rbri** [comment]
@svschouw-bb thanks for the report.

Maybe you can provide some samples to have test cases.
And of course every pr is welcome.

**Comment by svschouw-bb** [comment]
Test cases are pretty hard to create, since this is a performance issue, not a bug. I hope the unittest set is complete enough that any refactor of the parser does not break existing CSS parsing.

**Comment by rbri** [comment]
there is always a test missing :-)

Will also try to have a look - maybe we can get rid of the lookahead but i have to wake up my memories first

**Comment by svschouw-bb** [comment]
> Is there any reason to keep the whitespace in the token stream? Is there an annoying CSS feature that requires this?

Yes, there is, otherwise it is not possible to distinguish between `div .foo` and `div.foo`... sigh. This complicates matters.

**Comment by rbri** [comment]
css parsing is horrible - but i did already some minor cleanup

**Comment by rbri** [comment]
Have experimented today wit a similar solution. Looks like we are on the right path :-)

Am 14. April 2023 20:16:32 MESZ schrieb svschouw-bb ***@***.***>:

**Comment by rbri** [comment]
Hi @svschouw-bb 

have added your an my solution to a new branch - see https://github.com/HtmlUnit/htmlunit-cssparser/commit/1b63adfba840d50cc7c0f7ed409a9dbf2498c002

I can't find any real difference between all these implementation but maybe you have some more test cases. Please have a look....

**Comment by rbri** [comment]
Strange, i'm using openjdk8 here (and eclipse) and there was no notable difference.
Will check it again in the afternoon.

**Comment by svschouw-bb** [comment]
How long doe the performance test take there? It could be an issue at our end?

**Comment by rbri** [comment]
This is the version with lookahead(2)

![image](https://user-images.githubusercontent.com/2544132/232462694-e568df8c-efff-4d10-9e90-326bcaf610c7.png)

**Comment by rbri** [comment]
do you use any special vm or vm options?

**Comment by rbri** [comment]
your version
![image](https://user-images.githubusercontent.com/2544132/232464181-fa4e869b-d161-4f52-a4db-db612869385a.png)

**Comment by rbri** [comment]
my one
![image](https://user-images.githubusercontent.com/2544132/232464483-2e40f29d-941c-4859-9a1a-02633c4a0565.png)

**Comment by svschouw-bb** [comment]
Interesting... in maven it also runs very fast on my end... but in Eclipse very poorly.

**Comment by rbri** [comment]
Will think about it, but at least it was fun to dive (again) in the javacc mud

**Comment by rbri** [comment]
I think the lookahead(2) is the expected way for most readers - i like to stay with the current impl.
And we have the branch for further reference.
