### ISSUE TITLE
Css Font error

### ISSUE THREAD

**Issue by oswetto** [HtmlUnit/htmlunit-cssparser#2]
Hello @rbri 
when i parse this css "font:normal normal normal 14px/11 FontAwesome;" the parser return this error
null [1:1] Error in expression. (Invalid token "/". Was expecting one of: <NUMBER>, "inherit", <IDENT>, <STRING>, "-", <PLUS>, <HASH>, <EMS>, <EXS>, <LENGTH_PX>, <LENGTH_CM>, <LENGTH_MM>, <LENGTH_IN>, <LENGTH_PT>, <LENGTH_PC>, <ANGLE_DEG>, <ANGLE_RAD>, <ANGLE_GRAD>, <TIME_MS>, <TIME_S>, <FREQ_HZ>, <FREQ_KHZ>, <RESOLUTION_DPI>, <RESOLUTION_DPCM>, <PERCENTAGE>, <DIMENSION>, <UNICODE_RANGE>, <URI>, <FUNCTION>, "progid:".)

**Comment by rbri** [comment]
Sorry for the late response. Have added a test case but can not reproduce your problem.
