### ISSUE TITLE
Word inherit as css selector

### ISSUE THREAD

**Issue by oswetto** [HtmlUnit/htmlunit-cssparser#32]
Hi @rbri, if i use "inherit" as css selector i've error "Error in class selector. (Invalid token "inherit". Was expecting: <IDENT>.)"

`.inherit {
			height:auto;
			background-color:orange;
		}`

**Comment by rbri** [comment]
please try 3.5.0-SNAPSHOT

**Comment by oswetto** [comment]
Thanks work!
