### ISSUE TITLE
Pseudo-elements

### ISSUE THREAD

**Issue by oswetto** [HtmlUnit/htmlunit-cssparser#40]
Hello @rbri,
how detect pseudo-elements ::after ::before with htmlunit-cssparser

**Comment by rbri** [comment]
Hi Ivan,
long time not seen :-)

parsing "a:after" 
* creates an DESCENDANT_SELECTOR having
* an ELEMENT_NODE_SELECTOR as getAncestorSelector()
* an PSEUDO_ELEMENT_SELECTOR as getSimpleSelector() <- this is the pseudo one you are hopefully locking for

Hope you are fine
   Ronald
